#!/bin/sh
# -*- Mode: shell-script -*-
# Copyright (C) 2002 by Chmouel Boudjnah <chmouel@mandrakesoft.com>
# Redistribution of this file is permitted under the terms of the GNU 
# Public License (GPL)
# $Id: make-boot-splash-raw 263874 2009-11-30 18:28:33Z pterjan $

: ${splash_dir=/usr/share/bootsplash}

[ $# = 2 ] || { echo "usage: $0 <initrd> <theme>"; exit 1; }

initrd_file=$1
THEME=$2

tmp_dir=
tmp_initrd=

clean_tmp() {
    [ -n "$tmp_initrd" ] && rm -f "$tmp_initrd"
    [ -n "$tmp_dir" ] && rm -rf "$tmp_dir"
    rm -f "$initrd_file.tmp"
    return 0
}

clean_and_fail() {
    clean_tmp
    exit 1
}

initrd_file="$(readlink -f "$initrd_file")"

# warly: we cannot use file command which is in /usr/bin/
# initrd_type=`zcat /boot/initrd-2.6.14-2mdk.ramfs.img | file -`

if ( /bin/zcat $initrd_file 2> /dev/null | /bin/cpio -it &> /dev/null ); then
    if [ -x /usr/libexec/plymouth/plymouth-populate-initrd ]; then
	tmp_dir=`mktemp -d`
	[ -n "$tmp_dir" ] || clean_and_fail

	mkdir $tmp_dir/plymouth
	cd $tmp_dir/plymouth || clean_and_fail
	/bin/zcat $initrd_file | /bin/cpio -id --quiet || clean_and_fail
	/usr/libexec/plymouth/plymouth-populate-initrd -t . || clean_and_fail

	/bin/find . | \
		cpio -R 0:0 -H newc -o --quiet | \
		gzip -9 > $tmp_dir/initrd  || clean_and_fail
	mv -f $tmp_dir/initrd $initrd_file
    fi
else 
    $splash_dir/scripts/remove-boot-splash $initrd_file

    if [ -x /usr/libexec/plymouth/plymouth-populate-initrd ]; then
	tmp_initrd=`mktemp`
	tmp_dir=`mktemp -d`
	[ -n "$tmp_dir" ] && [ -n "$tmp_initrd" ] || clean_and_fail
	gzip -dc $initrd_file > $tmp_initrd 2> /dev/null || clean_and_fail
	mount -o loop $tmp_initrd $tmp_dir 2> /dev/null || clean_and_fail
	rm -rf $tmp_dir/usr/share/plymouth $tmp_dir/usr/lib*/plymouth
	/usr/libexec/plymouth/plymouth-populate-initrd -t $tmp_dir
	rc=$?
	umount $tmp_dir 2>/dev/null
	[ $rc -ne 0 ] && clean_and_fail
	gzip -9 -c $tmp_initrd > $initrd_file.tmp 2>/dev/null || clean_and_fail
	mv -f $initrd_file.tmp $initrd_file
    fi
fi

clean_tmp
