#!/bin/sh
# -*- Mode: shell-script -*-
# Copyright (C) 2002 by Chmouel Boudjnah <chmouel@mandrakesoft.com>
# Redistribution of this file is permitted under the terms of the GNU 
# Public License (GPL)
# $Id: make-boot-splash 261558 2009-10-07 17:07:28Z fcrozat $

: ${splash_dir=/usr/share/bootsplash}

[[ -f /etc/sysconfig/bootsplash ]] && source /etc/sysconfig/bootsplash
[[ -z $THEME ]] && THEME=OpenMandriva

[ $# = 2 ] || { echo "usage: $0 <initrd> <resolution>"; exit 1; }

initrd_file=$1
resolution=$2

plymouth-set-default-theme $THEME

$splash_dir/scripts/make-boot-splash-raw $initrd_file || exit 1
    
if [ -z "$DURING_INSTALL" ]; then
    $splash_dir/scripts/switch-themes -u
fi
